--- #YAML:1.0
name:               WWW-AfinimaKi
version:            0.3
abstract:           A AfinimaKi Recommendating Engine Client
author:
    - Matias Alejo Garcia ( matiu@cpan.org ) 
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              ~
    Encode:            ~
    perl:              5.008000
    RPC::XML:          ~
    RPC::XML::Client:  ~
    Test::More:        0.88
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
