---
abstract: 'A AfinimaKi Recommendating Engine Client'
author:
  - 'Matias Alejo Garcia ( matiu@cpan.org ) '
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-AfinimaKi
no_index:
  directory:
    - t
    - inc
requires:
  Cache::Memcached::Fast: 0
  Carp: 0
  Encode: 0
  RPC::XML: 0
  RPC::XML::Client: 0
  Test::More: 0.88
  perl: 5.008000
version: 0.83
